const ACTION_TYPES = {
    GET_VIDEO_PENDING: 'GET_VIDEO_PENDING',
    GET_VIDEO_SUCCESS: 'GET_VIDEO_SUCCESS',
    GET_VIDEO_ERROR: 'GET_VIDEO_ERROR',
    
    GET_CAMERA_PENDING: 'GET_CAMERA_PENDING',
    GET_CAMERA_SUCCESS: 'GET_CAMERA_SUCCESS',
    GET_CAMERA_ERROR: 'GET_CAMERA_ERROR',

    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_SUCCESS:'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_ERROR:'AUTH_LOGIN_ERROR' 
  };
  
export default ACTION_TYPES;